
import React, { useState, useEffect } from 'react';
// import GoogleLoginButton from '../../components/GoogleLoginButton';
import { Routes, Route, Navigate } from 'react-router-dom';
import './App.css';

export default function App() {

  function handleCallbackResponse(response) {
    console.log("Encoded JWT ID token: " + response.credential)
  }

  useEffect(() => {
    /* global google */
    window.google.accounts.id.initialize({
      client_id: process.env.REACT_APP_GOOGLE_CLIENT_ID,
      //If not woroking, try consolow logging this env variable somewhere? 
      callback: handleCallbackResponse  
    });

    window.google.accounts.id.renderButton(
      document.getElementById("signInDiv"),
      { theme: "outline", size: "large" }
    )

  }, []);

  const [isLoggedIn, setIsLoggedIn] = useState(false);
  // const [userName, setUserName] = useState('');

  // Handle sucessful login here. the credentialResponse object contains an 'access_token'
  // const handleSuccess = async (credentialResponse) => {
  //   console.log('Credential Response', credentialResponse);
  //   console.log('Access Token:', credentialResponse.access_token);
  //   setIsLoggedIn(true);
    
    // Now we will use the 'access_token' to make a request on the Google People API to
    // retrieve the user's profile information.

    // const profileResponse = await fetch('https://www.googleapis.com/oauth2/v1/userinfo?alt=json', {
    //   headers: {
    //     Authorization: `Bearer ${credentialResponse.access_token}`,
    //   },
    // });

    // const profileData = await profileResponse.json();
    // console.log('Profile Data:', profileData);
    // setUserName(profileData.name); // Set the user's name

    // If the above works, we'll begin fetching the calendar info next
  // };

  // const handleError = () => {
  //   console.log('Login Failed');
  //   // Handle faield login here
  // };

  return (
    <div className="App">
      
        <p>
         Welcome! Login to google below to see your upcoming events
        </p>
        <div id="signInDiv"></div>
        {/* <GoogleLoginButton
          onSuccess={handleSuccess}
          onError={handleError}
        />
         */}
        {/* A HTML version generated by google. Docs here - https://developers.google.com/identity/gsi/web/guides/overview */}
        {/* <div>
          <div id="g_id_onload"
     data-client_id="268382496628-vtmi063grulho776749kdj9jpf1pffvq.apps.googleusercontent.com"
     data-context="signin"
     data-ux_mode="popup"
     data-login_uri="http://localhost:3000"
     data-auto_prompt="false">
</div>

<div class="g_id_signin"
     data-type="standard"
     data-shape="pill"
     data-theme="outline"
     data-text="continue_with"
     data-size="large"
     data-logo_alignment="left">
</div>
</div> */}
        {isLoggedIn ? <p>You are Logged in!</p> : <p> Please login to see your events. </p>}
    </div>
  );
}

